package fonts.mooncake;
import android.app.Activity;
import android.content.Context;
import android.widget.Toast;
import fonts.Icone;


public class MooncakeIcone extends Icone {
 

	public static final int icon_accessibility = 0xe092;
	public static final int icon_add_contact = 0xe0a4;
	public static final int icon_adjust = 0xf042;
	public static final int icon_align_center = 0xf037;
	public static final int icon_align_justify = 0xf039;
	public static final int icon_align_left = 0xf036;
	public static final int icon_align_right = 0xf038;
	public static final int icon_android = 0xe094;
	public static final int icon_apple = 0xe093;
	public static final int icon_archive = 0xe0a0;
	public static final int icon_arrow_down = 0xe039;
	public static final int icon_arrow_left = 0xe037;
	public static final int icon_arrow_right = 0xe036;
	public static final int icon_arrow_up = 0xe038;
	public static final int icon_asterisk = 0xf069;
	public static final int icon_atom = 0xe08a;
	public static final int icon_attachment = 0xe069;
	public static final int icon_backward = 0xf04a;
	public static final int icon_bag = 0xe056;
	public static final int icon_ban_circle = 0xf05e;
	public static final int icon_barcode = 0xf02a;
	public static final int icon_bars = 0xe053;
	public static final int icon_battery = 0xe0a9;
	public static final int icon_bell = 0xe046;
	public static final int icon_bended_arrow_down = 0xe09b;
	public static final int icon_bended_arrow_left = 0xe04f;
	public static final int icon_bended_arrow_right = 0xe050;
	public static final int icon_bended_arrow_up = 0xe09a;
	public static final int icon_boat = 0xe0b3;
	public static final int icon_bold = 0xf032;
	public static final int icon_book = 0xf02d;
	public static final int icon_bookmark = 0xe027;
	public static final int icon_briefcase = 0xe006;
	public static final int icon_broadcast = 0xe011;
	public static final int icon_bullhorn = 0xf0a1;
	public static final int icon_business_card = 0xe0af;
	public static final int icon_calendar = 0xe0ac;
	public static final int icon_calendar_month = 0xe0a7;
	public static final int icon_camera = 0xe02a;
	public static final int icon_caret_down = 0xf0d7;
	public static final int icon_caret_left = 0xf0d9;
	public static final int icon_caret_right = 0xf0da;
	public static final int icon_caret_up = 0xf0d8;
	public static final int icon_cd = 0xe000;
	public static final int icon_certificate = 0xf0a3;
	public static final int icon_check = 0xf046;
	public static final int icon_chemical = 0xe0a5;
	public static final int icon_chevron_down = 0xf078;
	public static final int icon_chevron_left = 0xf053;
	public static final int icon_chevron_right = 0xf054;
	public static final int icon_chevron_up = 0xf077;
	public static final int icon_circle_arrow_down = 0xf0ab;
	public static final int icon_circle_arrow_left = 0xf0a9;
	public static final int icon_circle_arrow_right = 0xf0a8;
	public static final int icon_circle_arrow_up = 0xf0aa;
	public static final int icon_cloud = 0xe06e;
	public static final int icon_cloud_2 = 0xe073;
	public static final int icon_cloudy = 0xe072;
	public static final int icon_cloudy_2 = 0xe079;
	public static final int icon_clubs = 0xe087;
	public static final int icon_coffee = 0xe0b2;
	public static final int icon_cog = 0xe012;
	public static final int icon_cog_2 = 0xe013;
	public static final int icon_cog_3 = 0xe04d;
	public static final int icon_cogs = 0xf085;
	public static final int icon_comment = 0xe040;
	public static final int icon_comment_2 = 0xe0ad;
	public static final int icon_comments = 0xe03f;
	public static final int icon_comments_2 = 0xe0ae;
	public static final int icon_compass = 0xe051;
	public static final int icon_cyclop = 0xe099;
	public static final int icon_database = 0xe090;
	public static final int icon_diamonds = 0xe088;
	public static final int icon_download = 0xe002;
	public static final int icon_download_2 = 0xe003;
	public static final int icon_dribbble = 0xe0a1;
	public static final int icon_drops = 0xe0b4;
	public static final int icon_edit = 0xf044;
	public static final int icon_eject = 0xf052;
	public static final int icon_envelope = 0xe0b9;
	public static final int icon_exclamation_sign = 0xe00a;
	public static final int icon_eye_closed = 0xf070;
	public static final int icon_eye_open = 0xf06e;
	public static final int icon_facebook = 0xe052;
	public static final int icon_facetime_video = 0xe021;
	public static final int icon_fast_backward = 0xf049;
	public static final int icon_fast_forward = 0xf050;
	public static final int icon_feather = 0xe0ab;
	public static final int icon_file = 0xe01a;
	public static final int icon_file_css = 0xe097;
	public static final int icon_file_excel = 0xe018;
	public static final int icon_file_openoffice = 0xe016;
	public static final int icon_file_pdf = 0xe015;
	public static final int icon_file_powerpoint = 0xe019;
	public static final int icon_file_word = 0xe017;
	public static final int icon_file_xml = 0xe096;
	public static final int icon_file_zip = 0xe06b;
	public static final int icon_film = 0xf008;
	public static final int icon_film_camera = 0xe00e;
	public static final int icon_filter = 0xe049;
	public static final int icon_fire = 0xe03b;
	public static final int icon_flag = 0xe025;
	public static final int icon_flashlight = 0xe0b0;
	public static final int icon_folder_close = 0xe044;
	public static final int icon_folder_closed = 0xe042;
	public static final int icon_font = 0xf031;
	public static final int icon_food = 0xe055;
	public static final int icon_forward = 0xf04e;
	public static final int icon_frame = 0xe089;
	public static final int icon_fullscreen = 0xf0b2;
	public static final int icon_gauge = 0xe091;
	public static final int icon_gift = 0xf06b;
	public static final int icon_glass = 0xf000;
	public static final int icon_globe = 0xe047;
	public static final int icon_google_circles = 0xe09d;
	public static final int icon_graph = 0xe0a2;
	public static final int icon_hand_down = 0xf0a7;
	public static final int icon_hand_left = 0xf0a5;
	public static final int icon_hand_right = 0xf0a4;
	public static final int icon_hand_up = 0xf0a6;
	public static final int icon_hdd = 0xe045;
	public static final int icon_headphones = 0xe026;
	public static final int icon_heart = 0xf004;
	public static final int icon_history = 0xe058;
	public static final int icon_home = 0xf015;
	public static final int icon_home_2 = 0xe014;
	public static final int icon_hour_glass = 0xe05c;
	public static final int icon_html5 = 0xe098;
	public static final int icon_inbox = 0xe01d;
	public static final int icon_indent_left = 0xf03b;
	public static final int icon_indent_right = 0xf03c;
	public static final int icon_info_sign = 0xe034;
	public static final int icon_install = 0xe059;
	public static final int icon_italic = 0xf033;
	public static final int icon_key = 0xf084;
	public static final int icon_key_2 = 0xe05d;
	public static final int icon_keyboard = 0xe05e;
	public static final int icon_leaf = 0xe03a;
	public static final int icon_legal = 0xf0e3;
	public static final int icon_lemon = 0xf094;
	public static final int icon_light_bulb = 0xe05f;
	public static final int icon_lightning = 0xe070;
	public static final int icon_lightning_2 = 0xe07a;
	public static final int icon_link = 0xe060;
	public static final int icon_list = 0xf03a;
	public static final int icon_list_2 = 0xe022;
	public static final int icon_loading = 0xe054;
	public static final int icon_lock = 0xe023;
	public static final int icon_magic = 0xf0d0;
	public static final int icon_magnet = 0xf076;
	public static final int icon_map_marker = 0xe02d;
	public static final int icon_microphone = 0xe062;
	public static final int icon_minus = 0xf068;
	public static final int icon_minus_sign = 0xe030;
	public static final int icon_mobile_phone = 0xe065;
	public static final int icon_monitor = 0xe0b1;
	public static final int icon_moon = 0xe07c;
	public static final int icon_moon_2 = 0xe03d;
	public static final int icon_mouse = 0xe063;
	public static final int icon_move = 0xf047;
	public static final int icon_mug = 0xe0b5;
	public static final int icon_music = 0xe00c;
	public static final int icon_mute = 0xe09f;
	public static final int icon_network = 0xe0a6;
	public static final int icon_newspaper = 0xe08f;
	public static final int icon_off = 0xf011;
	public static final int icon_official = 0xe0b7;
	public static final int icon_ok = 0xf00c;
	public static final int icon_ok_circle = 0xf05d;
	public static final int icon_ok_sign = 0xe032;
	public static final int icon_pacman = 0xe067;
	public static final int icon_paper_airplane = 0xe068;
	public static final int icon_pause = 0xf04c;
	public static final int icon_pencil = 0xe02c;
	public static final int icon_phone = 0xe066;
	public static final int icon_picture = 0xe029;
	public static final int icon_pictures = 0xe02b;
	public static final int icon_pie_chart = 0xe05a;
	public static final int icon_pie_chart_2 = 0xe08e;
	public static final int icon_pie_chart_3 = 0xe08d;
	public static final int icon_plane = 0xe03c;
	public static final int icon_planet = 0xe08b;
	public static final int icon_play = 0xf04b;
	public static final int icon_play_circle = 0xe01e;
	public static final int icon_plus = 0xf067;
	public static final int icon_plus_sign = 0xe02f;
	public static final int icon_power = 0xe06c;
	public static final int icon_print = 0xe028;
	public static final int icon_progress_bar = 0xe0a8;
	public static final int icon_publish = 0xe0aa;
	public static final int icon_pushpin = 0xf08d;
	public static final int icon_qrcode = 0xf029;
	public static final int icon_question_sign = 0xe033;
	public static final int icon_radio = 0xe06d;
	public static final int icon_rainy = 0xe06f;
	public static final int icon_rainy_2 = 0xe071;
	public static final int icon_random = 0xe03e;
	public static final int icon_record = 0xe06a;
	public static final int icon_refresh = 0xe020;
	public static final int icon_remove = 0xf00d;
	public static final int icon_remove_circle = 0xf05c;
	public static final int icon_remove_sign = 0xe031;
	public static final int icon_repeat = 0xe01f;
	public static final int icon_reply = 0xe0b6;
	public static final int icon_resize_full = 0xf065;
	public static final int icon_resize_horizontal = 0xf07e;
	public static final int icon_resize_small = 0xf066;
	public static final int icon_resize_vertical = 0xf07d;
	public static final int icon_retweet = 0xe041;
	public static final int icon_road = 0xf018;
	public static final int icon_rss = 0xe07f;
	public static final int icon_rss_2 = 0xe080;
	public static final int icon_safari = 0xe081;
	public static final int icon_scissor = 0xf0c4;
	public static final int icon_screenshot = 0xe035;
	public static final int icon_search = 0xe00d;
	public static final int icon_settings = 0xe082;
	public static final int icon_share = 0xf045;
	public static final int icon_share_2 = 0xf064;
	public static final int icon_shopping_cart = 0xe04b;
	public static final int icon_sign_post = 0xe0a3;
	public static final int icon_signal = 0xe04c;
	public static final int icon_snowflake = 0xe07d;
	public static final int icon_snowy = 0xe076;
	public static final int icon_snowy_2 = 0xe077;
	public static final int icon_sort = 0xf0dc;
	public static final int icon_sort_down = 0xf0dd;
	public static final int icon_sort_up = 0xf0de;
	public static final int icon_sound = 0xe09e;
	public static final int icon_spades = 0xe086;
	public static final int icon_star = 0xf005;
	public static final int icon_star_empty = 0xf006;
	public static final int icon_stats = 0xe043;
	public static final int icon_stats_up = 0xe09c;
	public static final int icon_steering_wheel = 0xe04e;
	public static final int icon_step_backward = 0xf048;
	public static final int icon_step_forward = 0xf051;
	public static final int icon_stop = 0xf04d;
	public static final int icon_sun = 0xe07b;
	public static final int icon_sun_2 = 0xe07e;
	public static final int icon_support = 0xe05b;
	public static final int icon_t_shirt = 0xe04a;
	public static final int icon_table = 0xf0ce;
	public static final int icon_tablet = 0xe064;
	public static final int icon_tag = 0xf02b;
	public static final int icon_tags = 0xf02c;
	public static final int icon_tasks = 0xf0ae;
	public static final int icon_television = 0xe083;
	public static final int icon_text_height = 0xf034;
	public static final int icon_text_width = 0xf035;
	public static final int icon_th = 0xf00a;
	public static final int icon_th_large = 0xf009;
	public static final int icon_th_list = 0xf00b;
	public static final int icon_thumbs_down = 0xf088;
	public static final int icon_thumbs_up = 0xf087;
	public static final int icon_time = 0xe01b;
	public static final int icon_tint = 0xe02e;
	public static final int icon_tools = 0xe084;
	public static final int icon_trash = 0xf014;
	public static final int icon_tree = 0xe085;
	public static final int icon_trophy = 0xf091;
	public static final int icon_truck = 0xf0d1;
	public static final int icon_twitter = 0xe009;
	public static final int icon_umbrella = 0xf0e9;
	public static final int icon_unlink = 0xe061;
	public static final int icon_unlock = 0xe024;
	public static final int icon_upload = 0xe004;
	public static final int icon_upload_2 = 0xe005;
	public static final int icon_user = 0xe007;
	public static final int icon_users = 0xe008;
	public static final int icon_volume_down = 0xf027;
	public static final int icon_volume_off = 0xf026;
	public static final int icon_volume_up = 0xf028;
	public static final int icon_warning_sign = 0xe001;
	public static final int icon_weather = 0xe078;
	public static final int icon_windows = 0xe095;
	public static final int icon_windy = 0xe074;
	public static final int icon_windy_2 = 0xe075;
	public static final int icon_wrench = 0xe048;
	public static final int icon_yinyang = 0xe08c;
	public static final int icon_zoom_in = 0xe010;
	public static final int icon_zoom_out = 0xe00f;

	public MooncakeIcone(Context context) {
		super(context);
	}

	public MooncakeIcone(Context context, int iconeReference) {
		super(context, iconeReference);
	}


	public MooncakeIcone(Context context, int iconeReference, int size) {
		super(context, iconeReference, size);
	}


	@Override
	protected void initialiseTypeFace() {
		try {
			setTypeface(MooncakeUtil.getFont(getContext()));
		} catch(Exception e){
			Toast.makeText(getContext(), "Une police nécessaire n'est pas disponible sur votre appareil.", Toast.LENGTH_SHORT).show();
			try{Thread.sleep(Toast.LENGTH_LONG);}catch(Exception ex){};
			((Activity)getContext()).finish();
		}
	}
}
